# ============================================================
# LSOB_V7 – config.py
# ============================================================

START_BALANCE = 10000.0

SYMBOLS = [
    "BTCUSDT",
    "ETHUSDT",
    "SOLUSDT",
]

CANDLE_LIMIT = 300

TIMEFRAME_ENTRY = "1m"
TIMEFRAME_CONFIRMATION = "5m"
TIMEFRAME_TREND = "15m"

EMA_TREND_PERIOD = 200
ADX_PERIOD = 14
ADX_MINIMUM = 20.0
ATR_PERIOD = 14

SWING_LOOKBACK = 10
BOS_LOOKBACK = 10

SWEEP_TO_BOS_CANDLES = 12
BOS_TO_FVG_CANDLES = 4
SETUP_EXPIRY_CANDLES = 5

MIN_FVG_ATR_RATIO = 0.05
SWEEP_BUFFER_ATR = 0.05
STOP_BUFFER_ATR = 0.10

RISK_PER_TRADE_PERCENT = 0.25
LEVERAGE = 3
MAX_MARGIN_PERCENT = 20.0
COOLDOWN_CANDLES = 10

MAKER_FEE_PERCENT = 0.02
TAKER_FEE_PERCENT = 0.06

TAKER_SLIPPAGE_PERCENT = 0.02

TP1_R_MULTIPLE = 1.0
TP2_R_MULTIPLE = 1.2
TP3_R_MULTIPLE = 3.0

TP1_CLOSE_PERCENT = 70.0
TP2_CLOSE_PERCENT = 30.0
MAX_COST_TO_RISK_RATIO = 0.12